---
- name: ensure destination directory exists
  file: path={{ prefix }} owner={{ ansible_user }} group=www state=directory
  sudo: yes

- name: check out squirret source
  git: repo=git@github.com:aaronbean/squirret.git dest={{ prefix }} version={{ squirret_version }} accept_hostkey=true
  notify:
    - restart squirret

- name: install npm dependencies
  npm: path={{ prefix }} production=yes
  notify:
    - restart squirret

- name: start squirret now and on boot
  service: name={{ appname }}_{{ node_env }} enabled=yes state=started
  sudo: yes
